# Generated by Django 5.2.7 on 2026-07-21 00:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_lesson_price', models.DecimalField(decimal_places=2, default=Decimal('80'), max_digits=10)),
                ('monthly_package_price', models.DecimalField(decimal_places=2, default=Decimal('280'), max_digits=10)),
                ('package_lesson_count', models.PositiveIntegerField(default=4)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('notify_guardian_on_absence', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'إعدادات التسعير',
            },
        ),
    ]
