# Generated by Django 5.2.7 on 2026-07-21 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed_amount', 'مبلغ ثابت'), ('free', 'مجاني')], max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scope', models.CharField(choices=[('physical_only', 'حضوري فقط'), ('online_only', 'أونلاين فقط'), ('both', 'الاثنين')], max_length=15)),
                ('reason', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_granted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خصم طالب',
                'verbose_name_plural': 'خصومات الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
