# Generated by Django 5.2.7 on 2026-07-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='show_governorate_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='show_school_field',
            field=models.BooleanField(default=True),
        ),
    ]
