# Generated by Django 5.2.7 on 2026-07-21 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_pricingsettings_show_governorate_field_and_more'),
        ('courses', '0004_add_max_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('academic_year', models.CharField(choices=[('1st', 'الصف الأول الثانوي'), ('2nd', 'الصف الثاني الثانوي'), ('3rd', 'الصف الثالث الثانوي')], max_length=5)),
                ('schedule_description', models.CharField(blank=True, max_length=255)),
                ('lesson_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'مجموعة سنتر',
                'verbose_name_plural': 'مجموعات السنتر',
            },
        ),
        migrations.CreateModel(
            name='PhysicalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title_ar', models.CharField(max_length=200)),
                ('lesson_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.centergroup')),
                ('linked_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
            ],
            options={
                'verbose_name': 'حصة حضورية',
                'verbose_name_plural': 'الحصص الحضورية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('absent_excused', 'غائب بعذر'), ('makeup', 'تعويض')], max_length=15)),
                ('deducted', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.physicalsession')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
