# Generated by Django 5.0.6 on 2026-07-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_centergroup_physicalsession_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'باقة حصص',
                'verbose_name_plural': 'باقات الحصص',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='paid_via_package',
            field=models.BooleanField(default=False),
        ),
    ]
