# Generated by Django 5.2.7 on 2026-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('segment', models.CharField(choices=[('all', 'الكل'), ('students', 'الطلاب فقط'), ('center', 'طلاب السنتر'), ('online', 'طلاب الأونلاين'), ('1st', 'الصف الأول'), ('2nd', 'الصف الثاني'), ('3rd', 'الصف الثالث')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sending', 'جاري الإرسال'), ('done', 'مكتمل')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'حملة واتساب',
                'verbose_name_plural': 'حملات واتساب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('quiz_result', 'نتيجة الاختبار'), ('enrollment_confirmed', 'تأكيد التسجيل'), ('low_wallet', 'رصيد منخفض'), ('payment_success', 'نجاح الدفع'), ('new_lesson', 'درس جديد'), ('otp', 'رمز التحقق')], max_length=30, unique=True)),
                ('body_ar', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
            },
        ),
    ]
