# Generated by Django 5.2.7 on 2026-07-14 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('segment', models.CharField(choices=[('all', 'الكل'), ('students', 'الطلاب فقط'), ('center', 'طلاب السنتر'), ('online', 'طلاب الأونلاين'), ('1st', 'الصف الأول'), ('2nd', 'الصف الثاني'), ('3rd', 'الصف الثالث')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sending', 'جاري الإرسال'), ('done', 'مكتمل')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حملة إيميل',
                'verbose_name_plural': 'حملات الإيميل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('quiz_result', 'نتيجة الاختبار'), ('enrollment_confirmed', 'تأكيد التسجيل'), ('order_status', 'تغيير حالة الطلب'), ('campaign', 'رسائل تسويقية')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيل الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
                'unique_together': {('user', 'notif_type')},
            },
        ),
    ]
