# Generated by Django 5.2.7 on 2026-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_notification_preference_and_email_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glyph', models.CharField(default='𓂀', max_length=10)),
                ('heading', models.CharField(default='هتحس إنك قاعد في الفصل بالظبط!', max_length=300)),
                ('body', models.TextField(default='اعمل حسابك في دقيقة واحدة، واختار كورس صفّك، وابدأ أول حصة النهاردة.')),
                ('cta_text', models.CharField(default='إنشاء حساب جديد', max_length=100)),
                ('cta_link', models.CharField(default='/register', max_length=200)),
            ],
            options={
                'verbose_name': 'قسم دعوة التسجيل',
            },
        ),
        migrations.CreateModel(
            name='LandingDarkBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='طوّر مستواك، واتعلم التاريخ من أي مكان', max_length=300)),
                ('body', models.TextField(default='حصص مسجلة تقدر ترجعلها في أي وقت.')),
                ('check1', models.CharField(default='حصص مسجلة ترجعلها في أي وقت', max_length=200)),
                ('check2', models.CharField(default='مجموعات متابعة على التليجرام', max_length=200)),
                ('check3', models.CharField(default='مراجعات نهائية قبل الامتحان', max_length=200)),
                ('check4', models.CharField(blank=True, default='بنك أسئلة بآلاف الأسئلة', max_length=200)),
                ('cta_text', models.CharField(default='شوف كل الكورسات', max_length=100)),
                ('cta_link', models.CharField(default='#courses', max_length=200)),
            ],
            options={
                'verbose_name': 'قسم الميزات الداكن',
            },
        ),
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glyph', models.CharField(default='𓉐', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'ميزات القائد',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='منصة تعليم التاريخ للثانوية العامة', max_length=200)),
                ('heading', models.CharField(default='اتعلّم التاريخ مع القائد..', max_length=300)),
                ('heading_white', models.CharField(default='ومن أي مكان', max_length=200)),
                ('para', models.TextField(default='مع أ/ مصطفى عرفة — تجربة تعليمية مرنة وسهلة الوصول.')),
                ('cta1_text', models.CharField(default='تصفح الكورسات', max_length=100)),
                ('cta1_link', models.CharField(default='#courses', max_length=200)),
                ('cta2_text', models.CharField(blank=True, default='حسابي', max_length=100)),
                ('cta2_link', models.CharField(blank=True, default='#register', max_length=200)),
                ('stat1_num', models.CharField(default='+12,000', max_length=20)),
                ('stat1_label', models.CharField(default='طالب وطالبة', max_length=100)),
                ('stat2_num', models.CharField(default='+340', max_length=20)),
                ('stat2_label', models.CharField(default='حصة مسجلة', max_length=100)),
                ('stat3_num', models.CharField(default='%94', max_length=20)),
                ('stat3_label', models.CharField(default='نسبة نجاح +85', max_length=100)),
            ],
            options={
                'verbose_name': 'هيرو الصفحة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='LandingTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'شهادة طالب',
                'verbose_name_plural': 'شهادات الطلاب',
                'ordering': ['order'],
            },
        ),
    ]
