# Generated by Django 5.2.7 on 2026-07-15 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_email_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='المنزل', max_length=50)),
                ('governorate', models.CharField(choices=[('القاهرة', 'القاهرة'), ('الجيزة', 'الجيزة'), ('الإسكندرية', 'الإسكندرية'), ('الدقهلية', 'الدقهلية'), ('البحيرة', 'البحيرة'), ('الشرقية', 'الشرقية'), ('المنوفية', 'المنوفية'), ('الغربية', 'الغربية'), ('القليوبية', 'القليوبية'), ('أخرى', 'أخرى')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('street', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
