# Generated by Django 5.2.7 on 2026-07-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_centergroup_physicalsession_attendancerecord'),
        ('users', '0004_user_must_change_password_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.centergroup'),
        ),
    ]
