# Generated by Django 5.2.7 on 2026-07-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance_token',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
