# Generated by Django 5.0.6 on 2026-07-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_attendance_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prepaid_lessons_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
