# Generated by Django 5.2.7 on 2026-07-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_flash_sale_and_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='raw_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/uploads/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='aes_key',
            field=models.BinaryField(blank=True, default=b'', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='aes_key_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
