# Generated by Django 5.2.7 on 2026-07-21 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('updated', 'تعديل'), ('deleted', 'حذف'), ('overridden', 'تجاوز'), ('refunded', 'استرداد'), ('discount_granted', 'منح خصم'), ('discount_revoked', 'سحب خصم'), ('attendance_changed', 'تعديل حضور'), ('csv_imported', 'استيراد CSV'), ('access_granted', 'منح صلاحية'), ('access_revoked', 'سحب صلاحية'), ('debited', 'خصم من المحفظة'), ('credited', 'إيداع في المحفظة')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'سجل عملية',
                'verbose_name_plural': 'سجل العمليات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action', 'created_at'], name='audit_audit_actor_i_7a9569_idx')],
            },
        ),
    ]
