upstream elkaed_backend {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name elkaed.cloud www.elkaed.cloud;

    client_max_body_size 200M;

    location / {
        root /opt/elkaed/frontend/dist;
        add_header Cache-Control "no-cache";
        try_files $uri /index.html;
    }

    location /assets/ {
        root /opt/elkaed/frontend/dist;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /api/ {
        proxy_pass http://elkaed_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /django-admin/ {
        proxy_pass http://elkaed_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /opt/elkaed/backend/staticfiles/;
    }

    location /media/ {
        alias /opt/elkaed/backend/media/;
    }
}
