# Generated by Django 5.2.7 on 2026-07-14 15:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_flash_sale_and_bundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('mcq', 'اختيار متعدد'), ('tf', 'صح أو خطأ'), ('fill', 'اكمل الفراغ'), ('open', 'سؤال مقالي'), ('ordering', 'ترتيب')], max_length=10)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.PositiveIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('explanation_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions/')),
                ('wp_question_id', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'سؤال',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/answers/')),
                ('wp_answer_id', models.IntegerField(db_index=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'إجابة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='بالدقائق', null=True)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('attempts_allowed', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('hide_results', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_answers', models.BooleanField(default=False)),
                ('wp_post_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=9)),
                ('earned_marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('status', models.CharField(choices=[('in_progress', 'جاري'), ('submitted', 'مكتمل'), ('timed_out', 'انتهى الوقت')], default='in_progress', max_length=15)),
                ('result', models.CharField(blank=True, choices=[('pass', 'ناجح'), ('fail', 'راسب')], max_length=5, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('wp_attempt_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.TextField()),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_achieved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('wp_answer_id', models.IntegerField(db_index=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
            ],
            options={
                'verbose_name': 'إجابة محاولة',
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz', 'status'], name='quizzes_qui_student_8a16f3_idx'),
        ),
    ]
