# Generated by Django 5.2.7 on 2026-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_flash_sale_and_bundle'),
        ('courses', '0001_flash_sale_and_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='courses',
            field=models.ManyToManyField(related_name='bundles', to='courses.course'),
        ),
    ]
