# Generated by Django 5.2.7 on 2026-07-21 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_flash_sale_and_bundle'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_txns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('purchase', 'شراء كورس'), ('refund', 'استرداد'), ('csv_import', 'استيراد CSV'), ('attendance_present', 'حضور حصة'), ('attendance_absent', 'غياب عن حصة'), ('discount_adjustment', 'تعديل خصم'), ('package_credit', 'إيداع باقة'), ('admin_credit', 'إيداع إداري'), ('admin_debit', 'خصم إداري'), ('coupon', 'كوبون'), ('kanga_topup', 'شحن كانجا باي'), ('reversal', 'عكس معاملة'), ('bundle', 'شراء باقة كورسات')], max_length=30),
        ),
    ]
