# Generated by Django 5.2.7 on 2026-07-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentdiscount'),
        ('commerce', '0004_wallettransaction_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.studentdiscount'),
        ),
    ]
