# Generated by Django 5.0.6 on 2026-07-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_wallettransaction_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('purchase', 'شراء كورس'), ('refund', 'استرداد'), ('csv_import', 'استيراد CSV'), ('attendance_present', 'حضور حصة'), ('attendance_absent', 'غياب عن حصة'), ('discount_adjustment', 'تعديل خصم'), ('package_credit', 'إيداع باقة'), ('package_purchase', 'شراء باقة حصص'), ('admin_credit', 'إيداع إداري'), ('admin_debit', 'خصم إداري'), ('coupon', 'كوبون'), ('kanga_topup', 'شحن كانجا باي'), ('reversal', 'عكس معاملة'), ('bundle', 'شراء باقة كورسات')], max_length=30),
        ),
    ]
