# Generated by Django 5.2.7 on 2026-07-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_lesson_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
