# Generated by Django 5.2.7 on 2026-07-21 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_centergroup_physicalsession_attendancerecord'),
        ('courses', '0004_add_max_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_via', models.CharField(choices=[('absence', 'غياب'), ('manual', 'يدوي')], default='manual', max_length=10)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='courses.lesson')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.physicalsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'منح وصول لدرس',
                'verbose_name_plural': 'منح الوصول للدروس',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
