# Generated by Django 5.2.7 on 2026-07-21 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonaccessgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('material', 'ملف'), ('revision', 'مراجعة')], default='material', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('academic_year', models.CharField(blank=True, choices=[('', 'كل السنوات'), ('1st', 'الصف الأول الثانوي'), ('2nd', 'الصف الثاني الثانوي'), ('3rd', 'الصف الثالث الثانوي')], max_length=5)),
                ('visibility_student_type', models.CharField(blank=True, choices=[('', 'الاثنين'), ('center', 'سنتر'), ('online', 'أونلاين')], max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.lesson')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مادة تعليمية',
                'verbose_name_plural': 'المواد التعليمية',
                'ordering': ['-created_at'],
            },
        ),
    ]
