# Generated by Django 5.2.7 on 2026-07-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='view_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
